apiVersion: policy/v1

kind: PodDisruptionBudget

metadata:

  name: {{ include "go-service.fullname" . }}

spec:

  minAvailable: 1

  selector:

    matchLabels:

      app: {{ include "go-service.name" . }}
