apiVersion: v1
kind: Secret

metadata:
  name: {{ include "go-service.fullname" . }}

type: Opaque

{{- if .Values.secret }}
stringData:
{{- range $key,$value := .Values.secret }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}
