apiVersion: v1
kind: Service

metadata:
  name: {{ include "go-service.fullname" . }}

spec:

  selector:
    app: {{ include "go-service.name" . }}

  type: {{ .Values.service.type }}

  ports:

  - port: {{ .Values.service.port }}

    targetPort: 8080
