name: Build and Push Docker Image to Amazon ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: go-app

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t $ECR_REPOSITORY:${{ github.sha }} \
            -t $ECR_REPOSITORY:latest .

      - name: Tag Docker Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag $ECR_REPOSITORY:${{ github.sha }} \
            $REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

          docker tag $ECR_REPOSITORY:latest \
            $REGISTRY/$ECR_REPOSITORY:latest

      - name: Push Docker Images
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          docker push $REGISTRY/$ECR_REPOSITORY:latest
