name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod

      apply_target:
        description: "Resources to apply"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - iam
          - ecr
          - vpc
          - eks
          - asm

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-apply-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: iac/terraform

    env:
      TF_VAR_environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        shell: bash
        run: |
          TARGET="${{ github.event.inputs.apply_target }}"

          if [ "$TARGET" = "all" ]; then
            terraform plan \
              -var-file=environments/${{ github.event.inputs.environment }}.tfvars \
              -out=tfplan
          else

            case "$TARGET" in
              iam)
                MODULE="module.iam_role"
                ;;
              ecr)
                MODULE="module.ecr"
                ;;
              vpc)
                MODULE="module.vpc"
                ;;
              eks)
                MODULE="module.eks"
                ;;
              asm)
                MODULE="module.asm"
                ;;
              *)
                echo "Invalid target"
                exit 1
                ;;
            esac

            terraform plan \
              -target=$MODULE \
              -var-file=environments/${{ github.event.inputs.environment }}.tfvars \
              -out=tfplan
          fi

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Terraform Outputs
        if: success()
        run: terraform output
